stages:
- build
- deploy

variables:
  CI_REGISTRY_ID: service
  CI_REGISTRY_URI: registry.telexchange.ee
  CI_NAMESPACE: service_deploy
  CI_PROJECT_NAME: service_vendor
  CI_KUSTOMIZE_PATH: vendor
  CI_YAML_FILE_PREFIX: service-vendor
  CI_KUSTOMIZE_PATH_STAGE: vendor-stage
  CI_YAML_FILE_PREFIX_STAGE: service-vendor-stage

build_develop:
  image: docker:20.10
  stage: build
  script:
  - echo "$SSH_PRIVATE_KEY" | base64 -d | tr -d '\r' > ./key
  - docker build --ssh default=./key -t $CI_REGISTRY_URI/$CI_REGISTRY_ID/$CI_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG.$CI_COMMIT_SHORT_SHA .
  - docker login -u oauth -p $CI_REGISTRY_TOKEN $CI_REGISTRY_URI
  - docker push $CI_REGISTRY_URI/$CI_REGISTRY_ID/$CI_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG.$CI_COMMIT_SHORT_SHA
  - docker tag $CI_REGISTRY_URI/$CI_REGISTRY_ID/$CI_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG.$CI_COMMIT_SHORT_SHA $CI_REGISTRY_URI/$CI_REGISTRY_ID/$CI_NAMESPACE/$CI_PROJECT_NAME:latest
  - docker push $CI_REGISTRY_URI/$CI_REGISTRY_ID/$CI_NAMESPACE/$CI_PROJECT_NAME:latest
  only:
  - develop

deploy_develop:
  image: alpine/git
  stage: deploy
  tags:
  - shell
  script:
  - git clone https://token:$ACCESS_TOKEN@gitlab.telexchange.ee/service/service_deploy.git $CI_KUSTOMIZE_PATH
  - cd $CI_KUSTOMIZE_PATH
  - sed -i "s/service_deploy\/$CI_PROJECT_NAME.*/service_deploy\/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG.$CI_COMMIT_SHORT_SHA/g" kustomize/$CI_KUSTOMIZE_PATH/$CI_YAML_FILE_PREFIX-Deployment.yml
  - git add kustomize/$CI_KUSTOMIZE_PATH/$CI_YAML_FILE_PREFIX-Deployment.yml
  - git commit -m "up $CI_PROJECT_NAME"
  - git push origin master
  only:
  - develop

build_stage:
  image: docker:20.10
  stage: build
  script:
  - echo "$SSH_PRIVATE_KEY" | base64 -d | tr -d '\r' > ./key
  - docker build --ssh default=./key -t $CI_REGISTRY_URI/$CI_REGISTRY_ID/$CI_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG.$CI_COMMIT_SHORT_SHA .
  - docker login -u oauth -p $CI_REGISTRY_TOKEN $CI_REGISTRY_URI
  - docker push $CI_REGISTRY_URI/$CI_REGISTRY_ID/$CI_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG.$CI_COMMIT_SHORT_SHA
  - docker tag $CI_REGISTRY_URI/$CI_REGISTRY_ID/$CI_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG.$CI_COMMIT_SHORT_SHA $CI_REGISTRY_URI/$CI_REGISTRY_ID/$CI_NAMESPACE/$CI_PROJECT_NAME:latest
  - docker push $CI_REGISTRY_URI/$CI_REGISTRY_ID/$CI_NAMESPACE/$CI_PROJECT_NAME:latest
  only:
  - stage

deploy_stage:
  image: alpine/git
  stage: deploy
  tags:
  - shell
  script:
  - git clone https://token:$ACCESS_TOKEN@gitlab.telexchange.ee/service/service_deploy.git $CI_KUSTOMIZE_PATH_STAGE
  - cd $CI_KUSTOMIZE_PATH_STAGE
  - sed -i "s/service_deploy\/$CI_PROJECT_NAME.*/service_deploy\/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG.$CI_COMMIT_SHORT_SHA/g" kustomize/$CI_KUSTOMIZE_PATH_STAGE/$CI_YAML_FILE_PREFIX_STAGE-Deployment.yml
  - git add kustomize/$CI_KUSTOMIZE_PATH_STAGE/$CI_YAML_FILE_PREFIX_STAGE-Deployment.yml
  - git commit -m "up $CI_PROJECT_NAME"
  - git push origin master
  only:
  - stage
